### ISSUE TITLE
Change the logo in top left

### ISSUE THREAD

**Issue by NVNStickMan** [ShiniGandhi/JellyTheme#10]
I love this but I was wondering how I could change what the logo in the top left is this is the only theme with it and the only other area with this information possibly is in a locked reddit I am sorry if this annoys yall

**Comment by ghost** [comment]
sorry for the delay, i didn't get a notification for this issue
you can change the logo with these:
```css
.adminDrawerLogo img {
content:url("<logo link>")!important;
}

.imgLogoIcon {
content:url("<logo link>")!important;
}

.pageTitleWithLogo {
background-image:url("<logo link>")!important;
}
```
