### ISSUE TITLE
Main page doesnt show the background image.

### ISSUE THREAD

**Issue by Godwhitelight** [ShiniGandhi/JellyTheme#12]
My Custom CSS:
```css
@import url("https://cdn.jsdelivr.net/gh/ShiniGandhi/JellyTheme@latest/latest/JellyTheme-Cleaner.css");
:root {
--accent:red!important;
}
.layout-mobile .primaryImageWrapper > img {
display:block!important;
}
@import url("https://cdn.jsdelivr.net/gh/ShiniGandhi/JellyTheme@latest/latest/Cleaner-UI.css");
@import url("https://cdn.jsdelivr.net/gh/ShiniGandhi/JellyTheme@latest/latest/RTL-Fix.css");
@import url("https://cdn.jsdelivr.net/gh/ShiniGandhi/JellyTheme@latest/latest/Slim-ActiveDevices.css");
@import url("https://cdn.jsdelivr.net/gh/ShiniGandhi/JellyTheme@latest/latest/New-Libraries.css");
@import url("https://cdn.jsdelivr.net/gh/ShiniGandhi/JellyTheme@latest/latest/PlayerRevamp.css");
```
The result:
![image](https://github.com/ShiniGandhi/JellyTheme/assets/73111474/86c10bd3-1309-44b0-9b62-766c87c5710a)
